await page.mouse.click(1200, 400, {button:'right'});
await page.waitForTimeout(200);
await page.mouse.click(758, 850);
await page.waitForTimeout(900);
const a = await shot('18_resources_flyout');
await page.mouse.click(830, 850);
await page.waitForTimeout(900);
const b = await shot('19_town_flyout');
await page.mouse.click(613, 850);
await page.waitForTimeout(900);
const c = await shot('19b_storage_flyout');
await page.mouse.click(913, 850);
await page.waitForTimeout(900);
const d = await shot('19c_roads_flyout');
await page.mouse.click(985, 850);
await page.waitForTimeout(900);
const e = await shot('19d_clear_flyout');
await page.mouse.click(1058, 850);
await page.waitForTimeout(900);
const f = await shot('19e_demolish');
return [a,b,c,d,e,f, await page.evaluate(()=>window.__app.input.tool)];
